repos:
  # Pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: "README.*.md"
      - id: check-yaml
        args: ['--unsafe']  # Allow custom YAML tags
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: check-toml
      - id: check-docstring-first
      - id: check-executables-have-shebangs


  # Ruff for linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      - id: ruff-check
      - id: ruff-format

  - repo: local
    hooks:
      - id: check-generated-readmes
        name: Check generated readmes
        entry: mmg README.base.md --yes
        language: python
        additional_dependencies: [mmg]
        files: README.*.md
        pass_filenames: false


# Global configuration
default_stages: [pre-commit]
fail_fast: false
