name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      upload-coverage: true
      upload-artifacts: true
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
