# This workflow will install Python dependencies, run tests and lint with a
# variety of Python versions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.8.15"
    
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
    
    - name: Cache uv environment
      uses: actions/cache@v4
      with:
        path: .venv
        key: ${{ runner.os }}-uv-${{ matrix.python-version }}-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-uv-${{ matrix.python-version }}-
          ${{ runner.os }}-uv-
    
    - name: Sync dependencies
      run: uv sync --dev --extra dev
    
    - name: Lint with Ruff
      run: uv run ruff check .
    
    - name: Check format with Ruff
      run: uv run ruff format --check .
    
    - name: Test with pytest
      env:
        PYTHONPATH: src
      run: uv run pytest --cov=./ --cov-report=xml test
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
