name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      upload-coverage: false
      upload-artifacts: false
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: test
    environment: pypi
    permissions:
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv and setup the python version
        uses: astral-sh/setup-uv@v6
        with:
          version: latest
          python-version: 3.13
          enable-cache: false
          cache-dependency-glob: "**/pyproject.toml"

      - name: Install dependencies
        run: uv sync --all-groups --all-extras

      - name: Build package
        run: uv build

      - name: Publish to PyPI
        run: uv publish